# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'L:\Python\Projects\Learning\LuoOu_tools\scripts\ScriptPackages\Batch_attrManager\Batch_attrManager.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form_Main(object):
    def setupUi(self, Form_Main):
        Form_Main.setObjectName("Form_Main")
        Form_Main.resize(340, 324)
        Form_Main.setMinimumSize(QtCore.QSize(340, 300))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form_Main)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolBox = QtWidgets.QToolBox(Form_Main)
        self.toolBox.setEnabled(True)
        self.toolBox.setMinimumSize(QtCore.QSize(320, 300))
        self.toolBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setObjectName("toolBox")
        self.page_RsProxyMesh = QtWidgets.QWidget()
        self.page_RsProxyMesh.setGeometry(QtCore.QRect(0, 0, 322, 254))
        self.page_RsProxyMesh.setObjectName("page_RsProxyMesh")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.page_RsProxyMesh)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolBox_RPMTEB = QtWidgets.QToolBox(self.page_RsProxyMesh)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox_RPMTEB.sizePolicy().hasHeightForWidth())
        self.toolBox_RPMTEB.setSizePolicy(sizePolicy)
        self.toolBox_RPMTEB.setObjectName("toolBox_RPMTEB")
        self.page_RPMGeneral = QtWidgets.QWidget()
        self.page_RPMGeneral.setGeometry(QtCore.QRect(0, 0, 304, 184))
        self.page_RPMGeneral.setObjectName("page_RPMGeneral")
        self.layoutWidget = QtWidgets.QWidget(self.page_RPMGeneral)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 271, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_Dis = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_Dis.setMinimumSize(QtCore.QSize(131, 70))
        self.groupBox_Dis.setCheckable(True)
        self.groupBox_Dis.setChecked(False)
        self.groupBox_Dis.setObjectName("groupBox_Dis")
        self.radioButton_PreviewMesh = QtWidgets.QRadioButton(self.groupBox_Dis)
        self.radioButton_PreviewMesh.setGeometry(QtCore.QRect(10, 40, 95, 16))
        self.radioButton_PreviewMesh.setObjectName("radioButton_PreviewMesh")
        self.radioButton_BoundingBox = QtWidgets.QRadioButton(self.groupBox_Dis)
        self.radioButton_BoundingBox.setGeometry(QtCore.QRect(10, 20, 95, 16))
        self.radioButton_BoundingBox.setChecked(True)
        self.radioButton_BoundingBox.setObjectName("radioButton_BoundingBox")
        self.horizontalLayout_2.addWidget(self.groupBox_Dis)
        self.checkBox_RPMDISL = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_RPMDISL.setObjectName("checkBox_RPMDISL")
        self.horizontalLayout_2.addWidget(self.checkBox_RPMDISL)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_Mat = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_Mat.setMinimumSize(QtCore.QSize(131, 69))
        self.groupBox_Mat.setObjectName("groupBox_Mat")
        self.radioButton_FromScene = QtWidgets.QRadioButton(self.groupBox_Mat)
        self.radioButton_FromScene.setGeometry(QtCore.QRect(10, 40, 95, 16))
        self.radioButton_FromScene.setObjectName("radioButton_FromScene")
        self.radioButton_FromProxy = QtWidgets.QRadioButton(self.groupBox_Mat)
        self.radioButton_FromProxy.setGeometry(QtCore.QRect(10, 20, 95, 16))
        self.radioButton_FromProxy.setChecked(True)
        self.radioButton_FromProxy.setObjectName("radioButton_FromProxy")
        self.horizontalLayout_3.addWidget(self.groupBox_Mat)
        self.checkBox_RPMMATL = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_RPMMATL.setObjectName("checkBox_RPMMATL")
        self.horizontalLayout_3.addWidget(self.checkBox_RPMMATL)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.toolBox_RPMTEB.addItem(self.page_RPMGeneral, "")
        self.page_RPMOverrides = QtWidgets.QWidget()
        self.page_RPMOverrides.setGeometry(QtCore.QRect(0, 0, 304, 184))
        self.page_RPMOverrides.setObjectName("page_RPMOverrides")
        self.layoutWidget1 = QtWidgets.QWidget(self.page_RPMOverrides)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 261, 86))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_RMOBJ = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_RMOBJ.setTristate(False)
        self.checkBox_RMOBJ.setObjectName("checkBox_RMOBJ")
        self.verticalLayout_3.addWidget(self.checkBox_RMOBJ)
        self.checkBox_RMTES = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_RMTES.setObjectName("checkBox_RMTES")
        self.verticalLayout_3.addWidget(self.checkBox_RMTES)
        self.checkBox_RMUSE = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_RMUSE.setObjectName("checkBox_RMUSE")
        self.verticalLayout_3.addWidget(self.checkBox_RMUSE)
        self.checkBox_RMVIS = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_RMVIS.setObjectName("checkBox_RMVIS")
        self.verticalLayout_3.addWidget(self.checkBox_RMVIS)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_RMOBJL = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_RMOBJL.setObjectName("checkBox_RMOBJL")
        self.verticalLayout.addWidget(self.checkBox_RMOBJL)
        self.checkBox_RMTESL = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_RMTESL.setObjectName("checkBox_RMTESL")
        self.verticalLayout.addWidget(self.checkBox_RMTESL)
        self.checkBox_RMUSEL = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_RMUSEL.setObjectName("checkBox_RMUSEL")
        self.verticalLayout.addWidget(self.checkBox_RMUSEL)
        self.checkBox_RMVISL = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_RMVISL.setObjectName("checkBox_RMVISL")
        self.verticalLayout.addWidget(self.checkBox_RMVISL)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.toolBox_RPMTEB.addItem(self.page_RPMOverrides, "")
        self.horizontalLayout.addWidget(self.toolBox_RPMTEB)
        self.toolBox.addItem(self.page_RsProxyMesh, "")
        self.page_RsShape = QtWidgets.QWidget()
        self.page_RsShape.setGeometry(QtCore.QRect(0, 0, 322, 254))
        self.page_RsShape.setObjectName("page_RsShape")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_RsShape)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.toolBox_2 = QtWidgets.QToolBox(self.page_RsShape)
        self.toolBox_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox_2.sizePolicy().hasHeightForWidth())
        self.toolBox_2.setSizePolicy(sizePolicy)
        self.toolBox_2.setObjectName("toolBox_2")
        self.page_RSShapeattr = QtWidgets.QWidget()
        self.page_RSShapeattr.setGeometry(QtCore.QRect(0, 0, 304, 184))
        self.page_RSShapeattr.setObjectName("page_RSShapeattr")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page_RSShapeattr)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(70, 30, 160, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_RSHID = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_RSHID.setObjectName("pushButton_RSHID")
        self.verticalLayout_7.addWidget(self.pushButton_RSHID)
        self.pushButton_RSSHO = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_RSSHO.setObjectName("pushButton_RSSHO")
        self.verticalLayout_7.addWidget(self.pushButton_RSSHO)
        self.toolBox_2.addItem(self.page_RSShapeattr, "")
        self.page_RSLayerOverride = QtWidgets.QWidget()
        self.page_RSLayerOverride.setGeometry(QtCore.QRect(0, 0, 304, 184))
        self.page_RSLayerOverride.setObjectName("page_RSLayerOverride")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page_RSLayerOverride)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 301, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.toolBox_2.addItem(self.page_RSLayerOverride, "")
        self.verticalLayout_5.addWidget(self.toolBox_2)
        self.toolBox.addItem(self.page_RsShape, "")
        self.verticalLayout_4.addWidget(self.toolBox)

        self.retranslateUi(Form_Main)
        self.toolBox_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form_Main)

    def retranslateUi(self, Form_Main):
        _translate = QtCore.QCoreApplication.translate
        Form_Main.setWindowTitle(_translate("Form_Main", "attrManager"))
        self.groupBox_Dis.setTitle(_translate("Form_Main", "Display Mode"))
        self.radioButton_PreviewMesh.setText(_translate("Form_Main", "Preview Mesh"))
        self.radioButton_BoundingBox.setText(_translate("Form_Main", "Bounding Box"))
        self.checkBox_RPMDISL.setText(_translate("Form_Main", "Layer"))
        self.groupBox_Mat.setTitle(_translate("Form_Main", "Material Mode"))
        self.radioButton_FromScene.setText(_translate("Form_Main", "From Scene"))
        self.radioButton_FromProxy.setText(_translate("Form_Main", "From Proxy"))
        self.checkBox_RPMMATL.setText(_translate("Form_Main", "Layer"))
        self.toolBox_RPMTEB.setItemText(self.toolBox_RPMTEB.indexOf(self.page_RPMGeneral), _translate("Form_Main", "General"))
        self.checkBox_RMOBJ.setText(_translate("Form_Main", "Object ID"))
        self.checkBox_RMTES.setText(_translate("Form_Main", "Tessellation / Displacement"))
        self.checkBox_RMUSE.setText(_translate("Form_Main", "User Data"))
        self.checkBox_RMVIS.setText(_translate("Form_Main", "Visbility / Matte"))
        self.checkBox_RMOBJL.setText(_translate("Form_Main", "Layer"))
        self.checkBox_RMTESL.setText(_translate("Form_Main", "Layer"))
        self.checkBox_RMUSEL.setText(_translate("Form_Main", "Layer"))
        self.checkBox_RMVISL.setText(_translate("Form_Main", "Layer"))
        self.toolBox_RPMTEB.setItemText(self.toolBox_RPMTEB.indexOf(self.page_RPMOverrides), _translate("Form_Main", "Overrides"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_RsProxyMesh), _translate("Form_Main", "RsProxyMesh"))
        self.pushButton_RSHID.setText(_translate("Form_Main", "Hide All"))
        self.pushButton_RSSHO.setText(_translate("Form_Main", "Show All"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_RSShapeattr), _translate("Form_Main", "RsShapeattr"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_RSLayerOverride), _translate("Form_Main", "Layer Override"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_RsShape), _translate("Form_Main", "RsShape"))




