# -*- coding: UTF-8 -*-
#.@FileName:houdini.yml
#.@Date:2020-06-28:10:11
#.@Aurhor:LuoOu


#*****************************************************************************************************************************
# HOUDINI

version: &HOUDINI_VERSION 17.5.173
path:    &HOUDINI_PATH !join ["C:/Program Files/Side Effects Software/Houdini ", *HOUDINI_VERSION, /bin/houdinifx.exe]

start: *HOUDINI_PATH

renderer:
renderer_path:


ENV:
  PYTHONPATH:
    - !env [SOFTWARE_PATH]
    - !env [SOFTWARE_PATH, /scripts]
    - !env [SOFTWARE_PATH, /plugins]
#    - !env [DATA_PROJECT_PATH, /houdini]

#  HOUDINI_USER_PREF_DIR:
#    - !env_first [SOFTWARE_PATH]
  HOUDIN_PATH:
    - !env [SOFTWARE_PATH]

#     - !env [DATA_PROJECT_PATH, houdini]

  HOUDINI_SPLASH_FILE: !env [SOFTWARE_PATH, /icons/houdini_splash.png]

# MENU: plex/config/$project/houdini/MainMenuMaster.xml

SETTINGS:
