# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fcLocalTask.ui'
#
# Created: Wed Aug 19 15:23:41 2020
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_FcLoadTask(object):
    def setupUi(self, FcLoadTask):
        FcLoadTask.setObjectName("FcLoadTask")
        FcLoadTask.resize(720, 300)
        FcLoadTask.setMinimumSize(QtCore.QSize(720, 300))
        FcLoadTask.setAutoFillBackground(False)
        FcLoadTask.setStyleSheet("")
        self.layMain = QtWidgets.QHBoxLayout(FcLoadTask)
        self.layMain.setContentsMargins(-1, -1, -1, 4)
        self.layMain.setObjectName("layMain")
        self.widgetClass = QtWidgets.QWidget(FcLoadTask)
        self.widgetClass.setMaximumSize(QtCore.QSize(100, 16777215))
        self.widgetClass.setObjectName("widgetClass")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widgetClass)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lstModule = QtWidgets.QListWidget(self.widgetClass)
        self.lstModule.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lstModule.setStyleSheet("color: rgb(230, 230, 230);")
        self.lstModule.setFrameShape(QtWidgets.QFrame.Box)
        self.lstModule.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lstModule.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.lstModule.setTabKeyNavigation(False)
        self.lstModule.setDragEnabled(False)
        self.lstModule.setResizeMode(QtWidgets.QListView.Adjust)
        self.lstModule.setViewMode(QtWidgets.QListView.ListMode)
        self.lstModule.setUniformItemSizes(False)
        self.lstModule.setBatchSize(100)
        self.lstModule.setObjectName("lstModule")
        item = QtWidgets.QListWidgetItem()
        self.lstModule.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstModule.addItem(item)
        self.verticalLayout.addWidget(self.lstModule)
        self.lstClass = QtWidgets.QListWidget(self.widgetClass)
        self.lstClass.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lstClass.setStyleSheet("color: rgb(230, 230, 230);")
        self.lstClass.setFrameShape(QtWidgets.QFrame.Box)
        self.lstClass.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lstClass.setObjectName("lstClass")
        item = QtWidgets.QListWidgetItem()
        self.lstClass.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstClass.addItem(item)
        self.verticalLayout.addWidget(self.lstClass)
        self.layMain.addWidget(self.widgetClass)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lstEntity = QtWidgets.QListWidget(FcLoadTask)
        self.lstEntity.setMinimumSize(QtCore.QSize(120, 0))
        self.lstEntity.setStyleSheet("color: rgb(230, 230, 230);")
        self.lstEntity.setFrameShape(QtWidgets.QFrame.Box)
        self.lstEntity.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lstEntity.setObjectName("lstEntity")
        item = QtWidgets.QListWidgetItem()
        self.lstEntity.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstEntity.addItem(item)
        self.verticalLayout_6.addWidget(self.lstEntity)
        self.layMain.addLayout(self.verticalLayout_6)
        self.widgeteStep = QtWidgets.QWidget(FcLoadTask)
        self.widgeteStep.setMaximumSize(QtCore.QSize(100, 16777215))
        self.widgeteStep.setObjectName("widgeteStep")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgeteStep)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lstStep = QtWidgets.QListWidget(self.widgeteStep)
        self.lstStep.setStyleSheet("color: rgb(230, 230, 230);")
        self.lstStep.setFrameShape(QtWidgets.QFrame.Box)
        self.lstStep.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lstStep.setObjectName("lstStep")
        item = QtWidgets.QListWidgetItem()
        self.lstStep.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstStep.addItem(item)
        self.verticalLayout_2.addWidget(self.lstStep)
        self.layMain.addWidget(self.widgeteStep)
        self.widgeteMeta = QtWidgets.QWidget(FcLoadTask)
        self.widgeteMeta.setMinimumSize(QtCore.QSize(200, 0))
        self.widgeteMeta.setObjectName("widgeteMeta")
        self.layMeta = QtWidgets.QVBoxLayout(self.widgeteMeta)
        self.layMeta.setContentsMargins(0, 0, 0, 0)
        self.layMeta.setObjectName("layMeta")
        self.layMain.addWidget(self.widgeteMeta)

        self.retranslateUi(FcLoadTask)
        QtCore.QMetaObject.connectSlotsByName(FcLoadTask)
        FcLoadTask.setTabOrder(self.lstModule, self.lstClass)
        FcLoadTask.setTabOrder(self.lstClass, self.lstStep)

    def retranslateUi(self, FcLoadTask):
        _translate = QtCore.QCoreApplication.translate
        FcLoadTask.setWindowTitle(_translate("FcLoadTask", "LoadTask"))
        __sortingEnabled = self.lstModule.isSortingEnabled()
        self.lstModule.setSortingEnabled(False)
        item = self.lstModule.item(0)
        item.setText(_translate("FcLoadTask", "Asset"))
        item = self.lstModule.item(1)
        item.setText(_translate("FcLoadTask", "Shot"))
        self.lstModule.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.lstClass.isSortingEnabled()
        self.lstClass.setSortingEnabled(False)
        item = self.lstClass.item(0)
        item.setText(_translate("FcLoadTask", "Chars"))
        item = self.lstClass.item(1)
        item.setText(_translate("FcLoadTask", "Props"))
        self.lstClass.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.lstEntity.isSortingEnabled()
        self.lstEntity.setSortingEnabled(False)
        item = self.lstEntity.item(0)
        item.setText(_translate("FcLoadTask", "chars_001"))
        item = self.lstEntity.item(1)
        item.setText(_translate("FcLoadTask", "chars_002"))
        self.lstEntity.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.lstStep.isSortingEnabled()
        self.lstStep.setSortingEnabled(False)
        item = self.lstStep.item(0)
        item.setText(_translate("FcLoadTask", "mod"))
        item = self.lstStep.item(1)
        item.setText(_translate("FcLoadTask", "rig"))
        self.lstStep.setSortingEnabled(__sortingEnabled)

