# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fcLocalTask.ui'
#
# Created: Thu Aug 20 17:36:43 2020
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_FcLoadTask(object):
    def setupUi(self, FcLoadTask):
        FcLoadTask.setObjectName("FcLoadTask")
        FcLoadTask.resize(720, 300)
        FcLoadTask.setMinimumSize(QtCore.QSize(720, 300))
        FcLoadTask.setAutoFillBackground(False)
        FcLoadTask.setStyleSheet("")
        self.layMain = QtWidgets.QHBoxLayout(FcLoadTask)
        self.layMain.setContentsMargins(-1, -1, -1, 4)
        self.layMain.setObjectName("layMain")
        self.widgetClass = QtWidgets.QWidget(FcLoadTask)
        self.widgetClass.setMaximumSize(QtCore.QSize(100, 16777215))
        self.widgetClass.setObjectName("widgetClass")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widgetClass)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lstModule = QtWidgets.QListWidget(self.widgetClass)
        self.lstModule.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lstModule.setStyleSheet("color: rgb(230, 230, 230);")
        self.lstModule.setFrameShape(QtWidgets.QFrame.Box)
        self.lstModule.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lstModule.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.lstModule.setTabKeyNavigation(False)
        self.lstModule.setDragEnabled(False)
        self.lstModule.setResizeMode(QtWidgets.QListView.Adjust)
        self.lstModule.setViewMode(QtWidgets.QListView.ListMode)
        self.lstModule.setUniformItemSizes(False)
        self.lstModule.setBatchSize(100)
        self.lstModule.setObjectName("lstModule")
        item = QtWidgets.QListWidgetItem()
        self.lstModule.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstModule.addItem(item)
        self.verticalLayout.addWidget(self.lstModule)
        self.lstClass = QtWidgets.QListWidget(self.widgetClass)
        self.lstClass.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lstClass.setStyleSheet("color: rgb(230, 230, 230);")
        self.lstClass.setFrameShape(QtWidgets.QFrame.Box)
        self.lstClass.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lstClass.setObjectName("lstClass")
        item = QtWidgets.QListWidgetItem()
        self.lstClass.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstClass.addItem(item)
        self.verticalLayout.addWidget(self.lstClass)
        self.layMain.addWidget(self.widgetClass)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lstEntity = QtWidgets.QListWidget(FcLoadTask)
        self.lstEntity.setMinimumSize(QtCore.QSize(120, 0))
        self.lstEntity.setStyleSheet("color: rgb(230, 230, 230);")
        self.lstEntity.setFrameShape(QtWidgets.QFrame.Box)
        self.lstEntity.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lstEntity.setObjectName("lstEntity")
        item = QtWidgets.QListWidgetItem()
        self.lstEntity.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstEntity.addItem(item)
        self.verticalLayout_6.addWidget(self.lstEntity)
        self.layMain.addLayout(self.verticalLayout_6)
        self.widgeteStep = QtWidgets.QWidget(FcLoadTask)
        self.widgeteStep.setMaximumSize(QtCore.QSize(100, 16777215))
        self.widgeteStep.setObjectName("widgeteStep")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgeteStep)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lstStep = QtWidgets.QListWidget(self.widgeteStep)
        self.lstStep.setStyleSheet("color: rgb(230, 230, 230);")
        self.lstStep.setFrameShape(QtWidgets.QFrame.Box)
        self.lstStep.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lstStep.setObjectName("lstStep")
        item = QtWidgets.QListWidgetItem()
        self.lstStep.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstStep.addItem(item)
        self.verticalLayout_2.addWidget(self.lstStep)
        self.layMain.addWidget(self.widgeteStep)
        self.widgeteMeta = QtWidgets.QWidget(FcLoadTask)
        self.widgeteMeta.setMinimumSize(QtCore.QSize(200, 0))
        self.widgeteMeta.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widgeteMeta.setObjectName("widgeteMeta")
        self.layMeta = QtWidgets.QVBoxLayout(self.widgeteMeta)
        self.layMeta.setSpacing(0)
        self.layMeta.setContentsMargins(0, 0, 0, 0)
        self.layMeta.setObjectName("layMeta")
        self.horizontalWidget = QtWidgets.QWidget(self.widgeteMeta)
        self.horizontalWidget.setMinimumSize(QtCore.QSize(0, 25))
        self.horizontalWidget.setMaximumSize(QtCore.QSize(16777215, 25))
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.combVariant = QtWidgets.QComboBox(self.horizontalWidget)
        self.combVariant.setEnabled(True)
        self.combVariant.setObjectName("combVariant")
        self.horizontalLayout.addWidget(self.combVariant)
        self.combversion = QtWidgets.QComboBox(self.horizontalWidget)
        self.combversion.setObjectName("combversion")
        self.horizontalLayout.addWidget(self.combversion)
        self.layMeta.addWidget(self.horizontalWidget)
        self.verticalWidget_2 = QtWidgets.QWidget(self.widgeteMeta)
        self.verticalWidget_2.setMinimumSize(QtCore.QSize(0, 200))
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelPreview = QtWidgets.QLabel(self.verticalWidget_2)
        self.labelPreview.setMinimumSize(QtCore.QSize(200, 200))
        self.labelPreview.setMaximumSize(QtCore.QSize(200, 200))
        self.labelPreview.setText("")
        self.labelPreview.setObjectName("labelPreview")
        self.verticalLayout_4.addWidget(self.labelPreview)
        self.layMeta.addWidget(self.verticalWidget_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.layMeta.addLayout(self.horizontalLayout_3)
        self.horizontalWidget_2 = QtWidgets.QWidget(self.widgeteMeta)
        self.horizontalWidget_2.setMinimumSize(QtCore.QSize(0, 25))
        self.horizontalWidget_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnCreate = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.btnCreate.setObjectName("btnCreate")
        self.horizontalLayout_2.addWidget(self.btnCreate)
        self.btnLoad = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.btnLoad.setObjectName("btnLoad")
        self.horizontalLayout_2.addWidget(self.btnLoad)
        self.btnSave = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_2.addWidget(self.btnSave)
        self.layMeta.addWidget(self.horizontalWidget_2)
        self.layMain.addWidget(self.widgeteMeta)

        self.retranslateUi(FcLoadTask)
        QtCore.QMetaObject.connectSlotsByName(FcLoadTask)
        FcLoadTask.setTabOrder(self.lstModule, self.lstClass)
        FcLoadTask.setTabOrder(self.lstClass, self.lstStep)

    def retranslateUi(self, FcLoadTask):
        _translate = QtCore.QCoreApplication.translate
        FcLoadTask.setWindowTitle(_translate("FcLoadTask", "LoadTask"))
        __sortingEnabled = self.lstModule.isSortingEnabled()
        self.lstModule.setSortingEnabled(False)
        item = self.lstModule.item(0)
        item.setText(_translate("FcLoadTask", "Asset"))
        item = self.lstModule.item(1)
        item.setText(_translate("FcLoadTask", "Shot"))
        self.lstModule.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.lstClass.isSortingEnabled()
        self.lstClass.setSortingEnabled(False)
        item = self.lstClass.item(0)
        item.setText(_translate("FcLoadTask", "Chars"))
        item = self.lstClass.item(1)
        item.setText(_translate("FcLoadTask", "Props"))
        self.lstClass.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.lstEntity.isSortingEnabled()
        self.lstEntity.setSortingEnabled(False)
        item = self.lstEntity.item(0)
        item.setText(_translate("FcLoadTask", "chars_001"))
        item = self.lstEntity.item(1)
        item.setText(_translate("FcLoadTask", "chars_002"))
        self.lstEntity.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.lstStep.isSortingEnabled()
        self.lstStep.setSortingEnabled(False)
        item = self.lstStep.item(0)
        item.setText(_translate("FcLoadTask", "mod"))
        item = self.lstStep.item(1)
        item.setText(_translate("FcLoadTask", "rig"))
        self.lstStep.setSortingEnabled(__sortingEnabled)
        self.btnCreate.setText(_translate("FcLoadTask", "Create"))
        self.btnLoad.setText(_translate("FcLoadTask", "Load"))
        self.btnSave.setText(_translate("FcLoadTask", "Save"))

