# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fcUpVersion.ui'
#
# Created: Mon Aug 24 16:29:55 2020
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

import Qt
print Qt.__binding__
from Qt import QtCore, QtGui, QtWidgets

class Ui_FcUpVersion(object):
    def setupUi(self, FcUpVersion):
        FcUpVersion.setObjectName("FcUpVersion")
        FcUpVersion.resize(200, 100)
        FcUpVersion.setMinimumSize(QtCore.QSize(200, 100))
        FcUpVersion.setMaximumSize(QtCore.QSize(208, 100))
        FcUpVersion.setAutoFillBackground(False)
        FcUpVersion.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(FcUpVersion)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalWidget = QtWidgets.QWidget(FcUpVersion)
        self.verticalWidget.setObjectName("verticalWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.verticalWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.labelCurVer = QtWidgets.QLabel(self.verticalWidget)
        self.labelCurVer.setMaximumSize(QtCore.QSize(70, 16777215))
        self.labelCurVer.setObjectName("labelCurVer")
        self.horizontalLayout_3.addWidget(self.labelCurVer)
        self.verticalLayout_6.addWidget(self.verticalWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(15, -1, 15, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelver = QtWidgets.QLabel(FcUpVersion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelver.sizePolicy().hasHeightForWidth())
        self.labelver.setSizePolicy(sizePolicy)
        self.labelver.setTextFormat(QtCore.Qt.AutoText)
        self.labelver.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelver.setObjectName("labelver")
        self.horizontalLayout.addWidget(self.labelver)
        self.btnSubtract = QtWidgets.QPushButton(FcUpVersion)
        self.btnSubtract.setMaximumSize(QtCore.QSize(16, 20))
        self.btnSubtract.setObjectName("btnSubtract")
        self.horizontalLayout.addWidget(self.btnSubtract)
        self.lineVer = QtWidgets.QLineEdit(FcUpVersion)
        self.lineVer.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineVer.setMaxLength(4)
        self.lineVer.setCursorPosition(4)
        self.lineVer.setReadOnly(True)
        self.lineVer.setObjectName("lineVer")
        self.horizontalLayout.addWidget(self.lineVer)
        self.btnAdd = QtWidgets.QPushButton(FcUpVersion)
        self.btnAdd.setMaximumSize(QtCore.QSize(16, 20))
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout.addWidget(self.btnAdd)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalWidget1 = QtWidgets.QWidget(FcUpVersion)
        self.verticalWidget1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.verticalWidget1.setObjectName("verticalWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.verticalWidget1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnOk = QtWidgets.QPushButton(self.verticalWidget1)
        self.btnOk.setMinimumSize(QtCore.QSize(0, 25))
        self.btnOk.setObjectName("btnOk")
        self.horizontalLayout_2.addWidget(self.btnOk)
        self.btnClose = QtWidgets.QPushButton(self.verticalWidget1)
        self.btnClose.setMinimumSize(QtCore.QSize(0, 25))
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_2.addWidget(self.btnClose)
        self.verticalLayout_6.addWidget(self.verticalWidget1)
        self.verticalLayout.addLayout(self.verticalLayout_6)

        self.retranslateUi(FcUpVersion)
        QtCore.QMetaObject.connectSlotsByName(FcUpVersion)

    def retranslateUi(self, FcUpVersion):
        _translate = QtCore.QCoreApplication.translate
        FcUpVersion.setWindowTitle(_translate("FcUpVersion", "UpVersion"))
        self.label_2.setText(_translate("FcUpVersion", "current version:"))
        self.labelCurVer.setText(_translate("FcUpVersion", "v001"))
        self.labelver.setText(_translate("FcUpVersion", "upgrade to "))
        self.btnSubtract.setText(_translate("FcUpVersion", "-"))
        self.lineVer.setText(_translate("FcUpVersion", "v001"))
        self.btnAdd.setText(_translate("FcUpVersion", "+"))
        self.btnOk.setText(_translate("FcUpVersion", "OK"))
        self.btnClose.setText(_translate("FcUpVersion", "Close"))

